### ISSUE TITLE
invite tracker feature

### ISSUE THREAD

**Issue by heyk1n** [rmvtlwt/yuinyan#6]
Ref: https://github.com/discord/discord-api-spec/blob/main/specs/openapi_preview.json#L2430

**Comment by aureziaa** [comment]
Itu yg paramater `query` pake username atau ID?

**Comment by heyk1n** [comment]
> Itu yg paramater `query` pake username atau ID?

Kayaknya username sih, sama kayak di members tab

**Comment by aureziaa** [comment]
Endpoint yang ada di folder test beda sama yang itu
```ts
const membersSearch = await rest.post(`/guilds/${guildId}/members-search`);
```
dah coba request pake query atau limit belum di test itu?

**Comment by heyk1n** [comment]
> dah coba request pake `query` atau `limit` kah di test itu?

belum.. tapi ada yang bilang bisa pake `query` di search params nya

> kenapa request methodnya `POST` btw?

ada yang nyoba pake `GET` tapi dapet status `403`, sama kayak waktu kita nyoba akses guild security actions itu

**Comment by heyk1n** [comment]
eh.. setelah gw cek cek lagi kayaknya gw salah endpoint deh
`/members/search` endpoint lama jir🗿

**Comment by heyk1n** [comment]
> > eh.. setelah gw cek cek lagi kayaknya gw salah endpoint deh `/members/search` endpoint lama jir🗿
> 
> Apa coba. referensinya hapus aja, tapi endpoint yang `/members-search` kan udah masuk "planned", bisa kali sambil tes tes sekalian

wes, ni issue gw tutup dulu aje yak, re-open pas endpointnya resmi rilis

**Comment by heyk1n** [comment]
> > eh.. setelah gw cek cek lagi kayaknya gw salah endpoint deh `/members/search` endpoint lama jir🗿
> 
> Apa coba. referensinya hapus aja, tapi endpoint yang `/members-search` kan udah masuk "planned", bisa kali sambil tes tes sekalian

wes, ni issue gw tutup dulu aje yak, re-open pas endpointnya resmi rilis
